<?php

use ChrisMallory\FreeShippingProgressBar\ViewModel\Cart\ProgressBar;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var ProgressBar $viewModel */
$viewModel = $block->getData('viewModel');

?>
<?php if ($viewModel->isEnabled()): ?>
    <div class="freeship-progress">
        <?php if (!$viewModel->isFreeShippingEligible()): ?>
            <?php
                $freeshippingProgress = $viewModel->getFreeShippingCompletionPercent();
                $background = "background: linear-gradient(to right, #00b052 0%, #00b052 " . $freeshippingProgress . "%, lightgreen);";
                if ($freeshippingProgress > 90) {
                    $background = "background: linear-gradient(to right, #00b052 0%, #00b052 95%, lightgreen);";
                }
            ?>
            <p class="upsell">Add
                <span class="freeship-price">
                    <?= /* @noEscape */ $viewModel->getFormattedPrice($viewModel->getFreeShippingDifference()) ?>
                </span>
                more to get
                <span class="freeship-bold">FREE SHIPPING!</span>
            </p>
            <div class="freeship-progress-bar-wrapper">
                <span class="min"><?= /* @noEscape */ $viewModel->getFormattedPrice(0, 0) ?></span>
                <div class="freeship-progress-bar">
                    <div class="freeship-progress-bar-bg">
                        <div class="freeship-progress-bar-fill freeship-progress-bar-progress"
                             style="width: <?= /* @noEscape */ $viewModel->getFreeShippingCompletionPercent() ?>%; <?= $background ?>">
                        </div>
                    </div>
                </div>
                <span class="max">
                    <?= /* @noEscape */ $viewModel->getFormattedPrice($viewModel->getFreeShippingMinValue(), 0) ?>
                </span>
            </div>
        <?php else: ?>
            <div class="freeship-text">
                <p>Your Order Is Eligible for <span class="freeship-bold">FREE SHIPPING!</span></p>
            </div>
        <?php endif; ?>
    </div>
<?php endif ?>
