name: M2 PHPStan
on: [push, pull_request]

jobs:
    phpstan:
        name: M2 PHPStan
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: extdn/github-actions-m2/magento-phpstan@master
              with:
                  composer_name: chrismallory/module-freeshipping-progress-bar
